Revert "Delete STACK_ARRAY macro, and use of alloca"
This reverts commit 74b373f04a69b279e45b0792d86c594cb33d22c1.

Reason for revert: This breaks chromium, blocking webrtc from rolling.

...
In file included from ../../third_party/webrtc\rtc_base/strings/string_builder.h:23:
../../third_party/webrtc\rtc_base/string_utils.h(54,28): error: implicit conversion loses integer precision: 'std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >::size_type' (aka 'unsigned long long') to 'int' [-Werror,-Wshorten-64-to-32]
                        ws.size());

See https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8912652299012991936/+/steps/compile__with_patch_/0/stdout

Original change's description:
> Delete STACK_ARRAY macro, and use of alloca
> 
> Refactor the few uses of STACK_ARRAY to avoid an extra copy
> on the stack.
> 
> Bug: webrtc:6424
> Change-Id: I5c8f3c0381523db0ead31207d949df9a286c76ba
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/137806
> Commit-Queue: Niels Moller <nisse@webrtc.org>
> Reviewed-by: Karl Wiberg <kwiberg@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#28038}

TBR=kwiberg@webrtc.org,nisse@webrtc.org

Change-Id: I223fceab60855dde363cc9ce8375e8f5cca43c02
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: webrtc:6424
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/138209
Reviewed-by: Henrik Boström <hbos@webrtc.org>
Commit-Queue: Henrik Boström <hbos@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#28043}