Trimming unneeded dependencies in test:test_support_unittests.
When building test:test_support_unittests with is_official_build=true,
the linker fails with the following error:

duplicate symbol: webrtc::videocapturemodule::VideoCaptureImpl::Create(
char const*)
>>> defined in obj/modules/video_capture/video_capture_internal_impl/\
    video_capture_linux.o
>>> defined in obj/modules/video_capture/libvideo_capture.a(\
    video_capture_external.o)

After looking at both test:test_support_unittests and test:test_support,
it seems these targets had unused dependenicies. This CL removes them
and fixes the duplicated symbol error.

The GN flag is_official_build changes some configurations down in the
toolchain, that is probably why building with is_official_build=false
was not triggering the problem.

In any case, build targets in test/ need to be cleaned up because they
depend on too many things.

Bug: webrtc:9117
Change-Id: Icfdae3b5610f1c873ccdd0292c12ef946dea79af
Reviewed-on: https://webrtc-review.googlesource.com/67161
Reviewed-by: Patrik Höglund <phoglund@webrtc.org>
Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#22789}