Turn on the RTC_ENABLE_WIN_WGC build flag.
This CL enables the RTC_ENABLE_WIN_WGC build flag, which introduces a
dependency on the Win10 SDK v10.0.17763. There is no change in behavior
from enabling this flag.

Consumers of WebRTC that use an older version of the Win10 SDK will
see errors similar to:
fatal error: 'windows.graphics.capture.interop.h' file not found
fatal error: 'windows.graphics.capture.h' file not found

They should upgrade to this or a newer version (Chromium requires,
and thus WebRTC recommends, v10.0.19041). You can find instructions
here:
https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md

Alternatively, consumers can disable this build flag in their
downstream copies of the WebRTC repo.

Bug: webrtc:9273
Change-Id: Ic6bf3ef3e69b8ba0e4022e07832fa66b6bcc6740
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/215244
Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
Commit-Queue: Austin Orion <auorion@microsoft.com>
Cr-Commit-Position: refs/heads/master@{#33968}