Reland "Remove TaskQueue constructor that uses GlobalTaskQueueFactory"
This reverts commit 57f2a5485a4c83c8045d0dbe9db6281d6bcda847.

Reason for revert: the breakage addressed with a separate change
https://webrtc-review.googlesource.com/c/src/+/131398

Original change's description:
> Revert "Remove TaskQueue constructor that uses GlobalTaskQueueFactory"
> 
> This reverts commit 7b7485b796ad77809e3343f3256013488b418235.
> 
> Reason for revert: Breaks Chrome autoroll 
> 
> video/video_stream_decoder_impl.cc:28:7: error: no matching constructor for initialization of 'rtc::TaskQueue'
>       bookkeeping_queue_("video_stream_decoder_bookkeeping_queue"),
> 
> Original change's description:
> > Remove TaskQueue constructor that uses GlobalTaskQueueFactory
> > 
> > Bug: webrtc:10284
> > Change-Id: I9547fb7110222ce3a3c2323ae2a004024eab911e
> > Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/130471
> > Commit-Queue: Danil Chapovalov <danilchap@webrtc.org>
> > Reviewed-by: Karl Wiberg <kwiberg@webrtc.org>
> > Cr-Commit-Position: refs/heads/master@{#27464}
> 
> TBR=danilchap@webrtc.org,kwiberg@webrtc.org
> 
> # Not skipping CQ checks because original CL landed > 1 day ago.
> 
> Bug: webrtc:10284
> Change-Id: I7684f7c7d5501cc910ac9f9daa8ccf6bdb10f8e1
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/131338
> Reviewed-by: Florent Castelli <orphis@webrtc.org>
> Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
> Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#27491}

TBR=danilchap@webrtc.org,mbonadei@webrtc.org,kwiberg@webrtc.org,orphis@webrtc.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: webrtc:10284
Change-Id: I0a0544d4b82adaec468d3445b6554a7b94d52db5
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/132225
Commit-Queue: Danil Chapovalov <danilchap@webrtc.org>
Reviewed-by: Danil Chapovalov <danilchap@webrtc.org>
Reviewed-by: Florent Castelli <orphis@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#27537}